# Generated by Django 5.2.3 on 2025-06-18 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroPonto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11)),
                ('data', models.DateField()),
                ('entrada', models.DateTimeField(blank=True, null=True)),
                ('saida_almoco', models.DateTimeField(blank=True, null=True)),
                ('volta_almoco', models.DateTimeField(blank=True, null=True)),
                ('saida', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Registro de Ponto',
                'verbose_name_plural': 'Registros de Ponto',
                'unique_together': {('cpf', 'data')},
            },
        ),
    ]
