# Generated by Django 5.2.3 on 2025-07-30 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
