# Generated by Django 5.2.3 on 2025-08-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponto', '0003_cadastro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=10),
        ),
    ]
