# Generated by Django 5.2.3 on 2025-08-13 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponto', '0004_alter_cadastro_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='Ativo', max_length=10),
        ),
    ]
